# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Pull Request verification"
  lane :pull_request_verification do 
    xcversion(version: "~> 11.5.0")
    iOSSwiftLint
    scan(
      workspace: "CIStudies.xcworkspace/",
      scheme: "CIStudies",
      device: "iPhone 11"
    )

  end

  desc "Run iOS SwiftLint"
  private_lane :iOSSwiftLint do
    swiftlint(
    mode: :lint,      # SwiftLint mode: :lint (default) or :autocorrect
    ignore_exit_status: true    # Allow fastlane to continue even if SwiftLint returns a non-zero exit status
  )
  end

end
