default_platform(:ios)

platform :ios do
  desc "Pull Request verification"
  lane :pull_request_verification do 
    xcversion(version: "~> 11.5.0")
    iOSSwiftLint
    cocoapods
    scan(
      workspace: "CIStudies.xcworkspace/",
      scheme: "CIStudies",
      device: "iPhone 11"
    )
    run_tests(scheme: "CIStudies")

  end

  desc "Run iOS SwiftLint"
  private_lane :iOSSwiftLint do
    swiftlint(
    mode: :lint,      # SwiftLint mode: :lint (default) or :autocorrect
    ignore_exit_status: true    # Allow fastlane to continue even if SwiftLint returns a non-zero exit status
  )
  end


 desc "Build App, Testflight"
  lane :beta do
    sync_code_signing(type: "appstore")    # see code signing guide for more information
    build_app(scheme: "CIStudies")
    upload_to_testflight
  end

  desc "Release to AppStore"
  lane :release do
    capture_screenshots                  # generate new screenshots for the App Store
    sync_code_signing(type: "appstore")  # see code signing guide for more information
    build_app(scheme: "CIStudies")
    upload_to_app_store                  # upload your app to App Store Connect
    increment_build_number(
       build_number: app_store_build_number + 1,
       xcodeproj: "CIStudies.xcodeproj"
    )
  end

end
