name: CIStudies Pull Request

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
            
jobs:
    pr_verification:
        name: PR Check
        runs-on: macos-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Cache fastlane dependences
                uses: actions/cache@v2
                with:
                    path: ~/.gem
                    key: ${{ runner.os }}-gem-${{ hashFiles('Gemfile.lock') }}
         
            -   name: Install Fastlane
                run: bundle config set path '~/.gem' && bundle install

            -   name: install swiftLint
                run: brew install swiftlint

            -   name: execute Fastlane
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: bundle exec fastlane ios pull_request_verification
