name: CIStudies Release

on:
    workflow_dispatch:
        tags:
            - '*'
jobs:
    generate-release:
        name: Generate release
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2.1.0
              with:
                  fetch-depth: '0'
                  ref: 'master'
                  
            - name: Cache Fastlane Dependencies
                 uses: actions/cache@v2
                 with:
                       path: ~/.gem
                       key: ${{ runner.os }}-gem-${{ hashFiles('Gemfile.lock') }}

            - name: Install Fastlane
              run: bundle install
              
              
            - name: Deploy new version
              env:
                #REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
                #NAME_REPO_TOKEN: ${{ secrets.NAME_REPO_TOKEN }}
                #GITHUB_USER: ${{ secrets.NAME_REPO_TOKEN }}
                GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
                #COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
              run: bundle exec fastlane release
        
